{{/*
# 🐻‍❄️🏴‍☠️ Noel's Helm Charts: Curated catalog of Noel's Helm charts.: Helm Charts for Noel's software and other software I use on a day to day basis
# Copyright (c) 2024 Noel Towa <cutie@floofy.dev>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
*/}}

{{- if not .Values.config.existingMap }}
{{ include "ume.configuration.validateValues" . }}

apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ printf "%s-%s" (include "ume.fullname" .) .Values.config.mapName }}
    namespace: {{ .Release.Namespace }}
    annotations:
        {{- include "ume.annotations" . | nindent 6 }}
    labels:
        {{- include "ume.labels" . | nindent 6 }}
data:
    ume.hcl: |
        {{- include "common.tplvalues.render" (dict "value" .Values.deployment.config "context" $) | nindent 8 }}
{{- end }}
